name: sparrow_image_picker
description: Flutter plugin for selecting images from the Android and iOS image
  library, and taking new pictures with the camera.
repository: https://github.com/hanguangbaihuo/sparrow_image_picker/tree/master/sparrow_image_picker
version: 0.0.3

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.sparrowimagepicker
        pluginClass: ImagePickerPlugin
      ios:
        pluginClass: FLTImagePickerPlugin
      # web:
      #   default_package: sparrow_image_picker_for_web

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  # sparrow_image_picker_for_web: ^0.0.2
  sparrow_image_picker_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.10.0
  plugin_platform_interface: ^2.0.0
