name: sparrow_image_picker_for_web
description: Web platform implementation of sparrow_image_picker
repository: https://github.com/hanguangbaihuo/sparrow_image_picker/sparrow_image_picker_for_web

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: sparrow_image_picker
    platforms:
      web:
        pluginClass: ImagePickerPlugin
        fileName: sparrow_image_picker_for_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  sparrow_image_picker_platform_interface: ^0.0.1
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
